[PenTest_Config]
scan_all_port = false
use_invasive_methodology = false
scan_only_online = true


[LLM]
distribution = "mistral"
api_url = "https://api.mistral.ai/v1/"
model = "codestral-latest"

[Embedding]
distribution = "jina" 
model = "jina-clip-v2"

[Suite_config]
tool_list = ["nmap", "nikto"]

[Report_Format]
security_benchmark = "compliance_benchmark/OWASP TOP 10.pdf"
report_folder_location = "results/"

[Debugging]
state = true